keranjang/urls.py
from django.urls import path
from . import views

app_name = 'keranjang'

urlpatterns = [
    path('', views.keranjang, name='keranjang'),
    path('checkout/', views.checkout, name='checkout'),
    path('bayar/', views.bayar, name='bayar'),
    path('detail/', views.detail, name='detail')
]

kybe/urls.py
from django.urls import path
from . import views

app_name = 'kybe'

urlpatterns = [
    path('', views.restoran, name='allresto'),
    path('<str:pk>/',views.cariResto, name='cariresto'),
    path('hasil/<str:pk>/',views.resto, name='resto'),
    path('hasil/<str:pk>/cari/',views.restorans, name='data'),
]

ppw/urls.py
from django.urls import path
from . import views

app_name = 'ppw'

urlpatterns = [
    path('', views.index, name='index'),
]

tk1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ppw.urls')),
    path('extra/', include('extra.urls')),
    path('login/', include('loginApp.urls', namespace="loginApp")),
    path('cari/', include('kybe.urls')),
    path('keranjang/', include('keranjang.urls')),
    path('feedback/', include('feedback.urls')),
]

keranjang/models.py
from django.db import models
from ppw.models import Makanan

# Create your models here.
pmb1 = "Go-pay"
pmb2 = "Ovo"
pmb3 = "Debit"
PMB_CHOICES = (
    (pmb1,"Go-bay"),
    (pmb2,"Owo"),
    (pmb3,"Debit"),
)

pgm1 = "JNO"
pgm2 = "TUKI"
pgm3 = "Si Lambat"
PGM_CHOICES = (
    (pgm1,"JNO"),
    (pgm2,"TUKI"),
    (pgm3,"Si Lambat"),
)

class konfirmasi(models.Model):
    alamat = models.CharField('Alamat Pengiriman',max_length=1000,blank=False)
    pembayaran = models.CharField('Metode Pembayaran',choices= PMB_CHOICES, default=pmb3,blank=False,max_length=50)
    pengiriman = models.CharField('Metode Pengiriman',choices= PGM_CHOICES, default=pgm3,blank=False,max_length=50)
    noHP = models.CharField('Nomor Telefon',max_length=12,blank=False)
    catatan = models.CharField("Catatan",max_length=500,blank=True)
    def __str__(self):
        return f'{self.keranjang}'

class Beli(models.Model):
    makanan = models.ForeignKey(Makanan, on_delete=models.CASCADE)
    jumlah = models.IntegerField(default=0)
    totalharga = models.IntegerField(default=0)
    def __str__(self):
        return self.makanan

keranjang/forms.py
from django import forms
from .models import konfirmasi
from .models import PMB_CHOICES
from .models import PGM_CHOICES

class KonfirmasiForm(forms.ModelForm):
    class Meta:
        model = konfirmasi
        fields = ['alamat','pembayaran','pengiriman','noHP','catatan']
        widgets = {
            'alamat': forms.TextInput(attrs={'class':'form-control'}),
            'pengiriman': forms.Select(choices=PGM_CHOICES,attrs={'class':'form-control'}),
            'pembayaran': forms.Select(choices=PMB_CHOICES,attrs={'class':'form-control'}),
            'noHP': forms.TextInput(attrs={'class':'form-control'}),
            'catatan': forms.TextInput(attrs={'class':'form-control'})
        }

keranjang/views.py
from django.shortcuts import render, redirect
from ppw.models import Restoran, Makanan
from .models import konfirmasi, Beli
from .forms import KonfirmasiForm

# Create your views here.
def keranjang(request):
    keranjang = Makanan.objects.all()
    resto = Restoran.objects.all()
    args = {'makan':keranjang, 'resto':resto}
    return render(request, 'keranjang_landing.html', args)

def checkout(request):
    if request.method == "POST":
        form = KonfirmasiForm(request.POST)
        if form.is_valid() :
            data_konfirmasi = form.save()
            data_konfirmasi.save()
            return redirect('keranjang:bayar')
    else :
        form = KonfirmasiForm()
        makanan = Makanan.objects.all()
        args = {'show':makanan, 'form':form}
    return render(request, 'checkout.html', args)

def bayar(request):
    return render(request, 'bayar.html')

def detail(request):
    detail = konfirmasi.objects.order_by("noHP")
    response = {'detail':detail} 
    return render(request,'detail.html',response)

keranjang/templates/bayar.html
<!DOCTYPE html>
<html>
{% load static %}
{% include "navbar.html" %}
<head>
	<title>Bayar</title>

	<!-- file CSS -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Bree Serif" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Lilita+One&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="{% static 'style.css' %}">

	<!-- JS, Popper.js, and jQuery -->
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body style="background-image: url('/static/sectionbayar.jpg');
background-size: cover;">
	<div class="container">
		<div class="row"></div>
			<div class="col-md-12">
				<div class="card1" style="margin-top: 15em;border-radius: 100px;opacity: 0.9;">
					<div class="card body border3" style="background-color:  rgb(190, 73, 73);text-align: center;padding: 5em;">
						<h1 style="color: white;">Terimakasih, Pesanan anda sudah dalam proses!</h1>
					</div>
				</div>
				<div class="btn-checkout" style="padding: 10px;float: right;margin-top: 10em ;">
					<a href="{% url 'keranjang:detail' %}">
						<button class="btn btn-danger hover padding1">Semua Transaksi</button>
					</a>
				</div>
			</div>
		</div>
	</div>
</body>
</html>

keranjang/templates/checkout.html
<!DOCTYPE html>
{% include "navbar.html" %}
{% load static %}

<html>
<head>
	<title>Checkout</title>

	<!-- file CSS -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<link href="https://fonts.googleapis.com/css?family=Bree Serif" rel="stylesheet">
	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css2?family=Lilita+One&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="{% static 'style.css' %}">

	<!-- JS, Popper.js, and jQuery -->
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body style="background-color: #F3F3F3;">
	<div class="container">
		<div class="row padding2">

			<div class="col-md-8">
				{% if show %}
					{% for makanan in show %}
					<div class="row">
						<div class="col-md-4 margin">
							<img class= "fotomakanan" src="{{ makanan.foto }}">
						</div>
						<div class="col-md-8 margin">
							<p>{{ makanan.nama_makanan }}</p>
							<p>Lokasi : {{ makanan.restoran.lokasi }}</p>
						</div>
					</div>
					{% endfor %}
				{% endif %}
			</div>

			<div class="col-md-4">
				<form method="POST">
					<div class="card">
						<div class="card-body border2">
							{% csrf_token %}
							{% for fields in form %}
							{{ fields.label_tag }}
							{{ fields }}
							{% endfor %}
							<div class="btn-checkout" style="padding: 10px;">
								<a href="{% url 'keranjang:bayar' %}">
									<button class="btn btn-danger hover" style="margin-top: 10px;">Bayar</button>
								</a>
							</div>
						</div>
					</div>
				</form>			
			</div>
		</div>
	</div>
</body>
</html>

keranjang/templates/detail.html
<!DOCTYPE html>
<html>
{% load static %}
{% include "navbar.html" %}
<head>
	<title>Bayar</title>

	<!-- file CSS -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Bree Serif" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Lilita+One&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="{% static 'style.css' %}">

	<!-- JS, Popper.js, and jQuery -->
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body style="background-color: #F3F3F3;">
	<div class="container">
        <div class="row"></div>
            <div class="col-md-12"></div>
		        <div class="card1" style="margin-top: 15em;">
                    <div class="card body padding1" style="background-color:  rgb(190, 73, 73);text-align: center;">
						<h1 style="padding:10px;">Total Transaksi</h1>
						<table class="table">
							<thead >
								<tr>
									<th>Alamat</th>
									<th>Pembayaran</th>
									<th>Pengiriman</th>
									<th>Nomor HP</th>
									<th>Catatan</th>
								</tr>
							</thead>
							<tbody>
								{% csrf_token %}
								{% for fields in detail %}
								<tr>
									<td>{{ fields.alamat }}</td>
									<td>{{ fields.pembayaran }}</td>
									<td>{{ fields.pengiriman }}</td>
									<td>{{ fields.noHP }}</td>
									<td>{{ fields.catatan }}</td>
								</tr>
								{% endfor %}
							</tbody>
						</table>
					</div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

keranjang/templates/keranjang_landing.html
<!DOCTYPE html>
<html>
{% load static %}
{% include "navbar.html" %}
<head>

	<title>Keranjang</title>

	<!-- file CSS -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css2?family=Lilita+One&display=swap" rel="stylesheet">
	<link id="css" rel="stylesheet" href="{% static 'style.css' %}">

	<!-- JS, Popper.js, and jQuery -->
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body id="body" style="background-color: #F3F3F3;">
	<div class="container">
		<div class="section">
			<div class="row padding2">

				<div class="col-md-8">
					{% if makan %}
                		{% for makanan in makan %}
							<div class="row">
								<div class="col-lg-4 margin">
									<img class= "fotomakanan" src="{{ makanan.foto }}">
								</div>
								<div class="col-xl-8 margin">
									<p>{{ makanan.nama_makanan }}</p>
									<p>Lokasi : {{ makanan.restoran.lokasi }}</p>
								</div>
							</div>
						{% endfor %}
					{% endif %}
				</div>

				<div class="col-md-4">
					<div class="card1">
						<div class="card body padding1" style="background-color:  rgb(105, 97, 97);">
							<p>Total : </p>
							{% if user.is_authenticated %}
							<div class="btn-checkout">
								<a href="{% url 'keranjang:checkout' %}">
									<button class="btn btn-danger hover padding1">Checkout</button>
								</a>
							</div>

							{% else %}
							<section id="section">
								<div class="btn-checkout">
									<button id="button" class="btn btn-danger hover padding1">Checkout</button>
								</div>
							</section>
							<div class="btn-checkout" style="margin-top: 10px;"></div>
								<button id="X" class="btn btn-danger hover padding1">Untuk melakukan checkout, Harap login terlebih dahulu!!!</button>
							</div>
							{% endif %}
						</div>
					</div>
				</div>
			</div>

			<div class="row padding1">
				<div class="col-md-4" style="margin-right: auto;margin-left: auto;">
					<p class="border1 hover" style="text-align: center;">Rekomendasi Restoran</p>
				</div>
			</div>

			<div class="row border2">
				{% if resto %}
					{% for restoran in resto %}
						<div class="col-md-3">
							<div>
								<a href="{% url 'kybe:resto' restoran.id %}" class="link">
									<img class="foto-keranjang1" src="{{ restoran.foto }}">
								</a>
							</div>
						</div>
					{% endfor %}
				{% endif %}
			</div>

			<br>

		</div>
	</div>
	<div class="footer">

	</div>
	<br>
	<script type ="text/javascript" src="{% static 'pop.js' %}" charset="utf-8"></script>

	<div class="container-xl restoran">
		<div class="row text-right">
			<div class="col-sm-12">
				<button id="tombol" class="button" onclick="myFunction()">Dark mode</button>
			</div>
		</div>
	</div>

	<br>
	<br>

	<script>
		function myFunction() {
			var body = document.getElementById('body').style.backgroundColor;
			if (body == 'rgb(19, 41, 61)') {
				document.getElementById('body').style.color = '#13293D';
				document.getElementById('css').href = "{% static 'style.css' %}";
				document.getElementById('body').style.backgroundColor = '#F3F3F3';
				document.getElementById('tombol').innerHTML = "Dark Mode";
			} else {
				document.getElementById('body').style.color = '#F3F3F3';
				document.getElementById('css').href = "{% static 'stylegelap.css' %}";
				document.getElementById('body').style.backgroundColor = '#13293D';
				document.getElementById('tombol').innerHTML = "Light Mode";
			}
		}
	</script>
</body>
</html>