extra/urls.py
from django.urls import path
from . import views

app_name = 'extra'

urlpatterns = [
    path('', views.aboutus, name='aboutus'),
    path('helpcenter/', views.helpcenter, name='helpcenter'),
    path('collections/', views.collections, name='collections'),
    path('delete/<str:pk>/',  views.delete, name = 'delete'),
]

feedback/urls.py
from django.contrib import admin
from django.urls import path
from .views import FeedbackList, FeedbackComplete, FeedbackDelete
from django.conf import settings
from django.conf.urls.static import static

app_name = 'feedback'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', FeedbackList.as_view(), name='req_list_url'),
    # path('request/', RequestList.as_view(), name='req_list_url'),
    path('<str:id>/completed/', FeedbackComplete.as_view(), name="req_complete_url"),
    path('<str:id>/delete/', FeedbackDelete.as_view(), name="req_delete_url"),
    ]

kybe/urls.py
from django.urls import path
from . import views

app_name = 'kybe'

urlpatterns = [
    path('', views.restoran, name='allresto'),
    path('<str:pk>/',views.cariResto, name='cariresto'),
    path('hasil/<str:pk>/',views.resto, name='resto'),
    path('hasil/<str:pk>/cari/',views.restorans, name='data'),
]

loginApp/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import login_page, register_page, logout_page

app_name = 'login'

urlpatterns = [
    path('', login_page, name='login'),
    path('register/', register_page, name='register'),
    path('logout/', logout_page, name='logout') 
] 

ppw/urls.py
from django.urls import path
from . import views

app_name = 'ppw'

urlpatterns = [
    path('', views.index, name='index'),
]

tk1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ppw.urls')),
    path('extra/', include('extra.urls')),
    path('login/', include('loginApp.urls', namespace="loginApp")),
    path('cari/', include('kybe.urls')),
    path('keranjang/', include('keranjang.urls')),
    path('feedback/', include('feedback.urls')),
]

ppw/models.py
from django.db import models

class Restoran(models.Model):
    nama_restoran = models.CharField(max_length=100, default='Unknown Restaurant')
    lokasi = models.CharField(max_length=100, default='Jakarta')
    kategori = models.CharField(max_length=100, default='Fast Food')
    foto = models.CharField(max_length=255, default='none')
    rating = models.DecimalField(max_digits=2, decimal_places=1, default='0.0')
    def __str__(self):
        return self.nama_restoran

class Makanan(models.Model):
    nama_makanan = models.CharField(max_length=100, default='None')
    restoran = models.ForeignKey(Restoran, on_delete=models.CASCADE)
    harga = models.IntegerField(default=0)
    foto = models.CharField(max_length=255, default='none')
    def __str__(self):
        return self.nama_makanan

ppw/forms.py
from django import forms
from .models import Makanan

class Pembelian(forms.Form):
    beli = forms.IntegerField(label="Masukkan Jumlah", widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Masukkan Jumlah',
        'required': False,
    }))

ppw/views.py
from django.shortcuts import render
from .models import Restoran, Makanan
from kybe.forms import Pencarian
from kybe.views import restoran, cariResto
from kybe.models import Review

def tambahRating():
    show = Restoran.objects.all()
    for resto in show:
        pk = resto
        review = Review.objects.filter(resto=pk)
        nilai = 0
        jumlah = 0
        for rate in review:
            nilai += rate.rating
            jumlah += 1
        nilai /= jumlah
        nilai = round(nilai, 1)
        resto.rating = nilai
        resto.save()

def index(request):
    if request.method ==  "GET":
        tambahRating()
        show = Restoran.objects.all()
        form = Pencarian
        args = {'show':show, 'form':form}
        return render(request, 'index.html', args)
    else:
        return(restoran(request))

ppw/templates/footer.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'navbar.css' %}">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <!-- <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script> -->
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark topnav">
      <a class="navbar-link" href="{% url 'ppw:index' %}">
        <h5 class="home teksnav">OrderIn</h5>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav kanan">
          {% if user.is_authenticated %}
          <a class="nav-link" href="{% url 'feedback:req_list_url'%}">
            <h5 class="teksnav">Feedback</h5>
          </a>
          {% endif %}
          <a class="nav-link" href="{% url 'extra:aboutus'%}">
            <h5 class="teksnav">About Us</h5>
          </a>
          <a class="nav-link" href="{% url 'extra:helpcenter'%}">
            <h5 class="teksnav">Help Center</h5>
          </a>
        </div>
      </div>
    </nav>
  </body>
</html>

ppw/templates/index.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
    {% include "navbar.html" %}
    
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link id="css" rel="stylesheet" type="text/css" href="{% static 'index.css' %}">
        <title>Homepage</title>
    </head>

    <body id="body" style="background-color: #F3F3F3;">
        <div class="container-xl">
            <form method="POST">
                {% csrf_token %}
                <div class="row cari">
                    <div class="col-lg-12">
                        {{ form.cari }}
                    </div>
                </div>
                <div class="row text-center justify-content-center">
                    <div class="col-sm-12">
                        <button class="submit" type="submit">Cari</button>
                    </div>
                </div>
            </form>
        </div>

        <div class="container-xl restoran">
            <div class="row text-left">
                <div class="col-sm-12">
                    <h2 class="buka">Mau order?</h2>
                    <h3 class="buka"><b>OrderIn</b> aja kuy</h3>
                </div>
            </div>
        </div>
        <br>

        <div class="container">
            {% if show %}
                {% for resto in show %}
                <a href="{% url 'kybe:resto' resto.id %}" class="link">
                    <div class="row batas">
                        <div class="col-lg-4 baris">
                            <img class="foto" src="{{ resto.foto }}" alt="Images">
                        </div>
                        <div class="col-md-8 baris">
                            <h3 class="deskripsi">{{ resto.nama_restoran }}</h3>
                            <table class="tabel">
                                <tr>
                                    <td class="head">Lokasi</td>
                                    <td>: {{ resto.lokasi }}</td>
                                </tr>
                                <tr>
                                    <td class="head">Jenis</td>
                                    <td>: {{ resto.kategori }}</td>
                                </tr>
                                <tr>
                                    <td class="head">Rating</td>
                                    <td>: {{ resto.rating }}/5.0</td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </a>
                {% endfor %}
            {% endif %}
        </div>

        <div class="container-xl restoran">
            <div class="row text-right">
                <div class="col-sm-12">
                    <button id="button" class="button" onclick="myFunction()">Dark mode</button>
                </div>
            </div>
        </div>

        <br>
        <br>

        <script>
            function myFunction() {
                var body = document.getElementById('body').style.backgroundColor;
                if (body == 'rgb(19, 41, 61)') {
                    document.getElementById('body').style.backgroundColor = '#F3F3F3';
                    document.getElementById('css').href = "{% static 'index.css' %}";
                    document.getElementById('button').innerHTML = "Dark Mode";
                } else {
                    document.getElementById('body').style.backgroundColor = '#13293D';
                    document.getElementById('css').href = "{% static 'gelap.css' %}";
                    document.getElementById('button').innerHTML = "Light Mode";
                }
            }
        </script>
    </body>

    {% include "footer.html" %}
</html>

ppw/templates/navbar.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'navbar.css' %}">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark topnav">
      <a class="navbar-link" href="{% url 'ppw:index' %}">
        <h5 class="home teksnav">OrderIn</h5>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav kanan">
          <a class="nav-link" href="{% url 'keranjang:keranjang' %}">
            <img class="keranjang teksnav" src="{% static 'Images/cart.png' %}" alt="Keranjang">
          </a>
          {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'ppw:index' %}">
              <h5 class="teksnav">{{user.username}}</h5>
            </a>
            <a class="nav-link" href="{% url 'loginApp:logout'%}">
              <h5 class="teksnav">Keluar</h5>
            </a>

          {% else %}
            <a class="nav-link" href="{% url 'loginApp:login'%}">
              <h5 class="teksnav">Masuk</h5>
            </a>
            <a class="nav-link" href="{% url 'loginApp:register'%}">
              <h5 class="teksnav">Daftar</h5>
            </a>
          {% endif %}
        </div>
      </div>
    </nav>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

  </body>
</html>