extra/urls.py
from django.urls import path
from . import views

app_name = 'extra'

urlpatterns = [
    path('', views.aboutus, name='aboutus'),
    path('helpcenter/', views.helpcenter, name='helpcenter'),
    path('collections/', views.collections, name='collections'),
    path('delete/<str:pk>/',  views.delete, name = 'delete'),
]

keranjang/urls.py
from django.urls import path
from . import views

app_name = 'keranjang'

urlpatterns = [
    path('', views.keranjang, name='keranjang'),
    path('checkout/', views.checkout, name='checkout'),
    path('bayar/', views.bayar, name='bayar'),
    path('detail/', views.detail, name='detail')
]

loginApp/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import login_page, register_page, logout_page

app_name = 'login'

urlpatterns = [
    path('', login_page, name='login'),
    path('register/', register_page, name='register'),
    path('logout/', logout_page, name='logout') 
] 

ppw/urls.py
from django.urls import path
from . import views

app_name = 'ppw'

urlpatterns = [
    path('', views.index, name='index'),
]

tk1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ppw.urls')),
    path('extra/', include('extra.urls')),
    path('login/', include('loginApp.urls', namespace="loginApp")),
    path('cari/', include('kybe.urls')),
    path('keranjang/', include('keranjang.urls')),
    path('feedback/', include('feedback.urls')),
]

extra/models.py
from django.db import models

# Create your models here.

class Question_and_Answer(models.Model):
	Question = models.CharField(max_length = 200)
	Answer = models.TextField()

	# def __str__(self):
	# 	return self.Question

class Quest(models.Model):
	Question = models.CharField(max_length = 200)

	# def __str__(self):
	# 	return self.Question

extra/forms.py
from django.forms import ModelForm
from .models import Question_and_Answer, Quest

class QnAForm(ModelForm):
	class Meta:
		model = Question_and_Answer
		fields = '__all__'

class QuestForm(ModelForm):
	class Meta:
		model = Quest
		fields = '__all__'

extra/views.py
from django.shortcuts import render, redirect
from .forms import QnAForm, QuestForm
from .models import Question_and_Answer, Quest


def aboutus(request):
	context  = {}
	return render(request, 'aboutus.html', context)

def helpcenter(request):
	result = Question_and_Answer.objects.all()
	form = QuestForm()

	if request.method == "POST":
		form = QuestForm(request.POST)
		if form.is_valid():
			form.save()
		return redirect('extra:helpcenter')

	context = {'result' : result, 'form':form}
	return render(request, 'helpcenter.html', context)

def collections(request):
	result = Quest.objects.all()
	form = QnAForm()

	if request.method == "POST":
		form = QnAForm(request.POST)
		if form.is_valid():
			form.save()
		return redirect('extra:helpcenter')

	context = {'result' : result,'form':form}
	return render(request, 'collections.html',context)

def delete(request, pk):
	item = Quest.objects.get(id = pk)

	if request.method == "POST":
		item.delete()
		return redirect('extra:collections')


	context = {'item':item}
	return render(request, 'deleting.html', context)

extra/templates/aboutus.html
{% load static %}
{% include "navbar.html" %}
<head>
	<link id="css" rel="stylesheet" href="{% static '/css/styles.css' %}">
</head>

<body id="body">
	<img src="{% static '/images/uppercover.png' %}" alt="AboutUs" style="width: 100%;">

	<div id = "upper" class = "upper" >
		<p style="margin-bottom: 0px; font-size:1.25vw;">
			Kami membuat web yang dapat menghubungkan antara pembeli dan penjual, seorang pembeli tidak perlu keluar rumah untuk mendapatkan makanan, cukup mengakses web kami di device kalian.
		</p>
	</div>

	<br>

	<div class="topmain">
		<h3 style="">Our goal is to Make your stomach full</h3>
		<p>You guys hungry? Order then</p>
		<hr style="margin-right: 80%; border-color: red;">
		<img src="{% static '/images/mainchef.jpg' %}" alt="AboutUs" style="width: 100%; padding-bottom: 10px;">

		<br>	
		<h3>Guarantee</h3>
		<hr style="margin-right: 80%; border-color: red;">
		<p>Kalian Bakal sangatlah puas dengan aplikasi kami. Selain cuma nyedian makanan, pastinya juga kalian akan senang soalnya transaksi dan sebagainya juga sudah kami sediakan. Dimasa pandemi ini juga banyak restoran yang tutup. Selain kita juga menguntungan costumer, Kita juga bisa menguntungkan para pembisnis</p>
	</div>
	<br>

	<div id= "middlemain" class  = "middlemain">
		<h3>The 3 Bang Django Pillars</h3>
		<hr style="margin-right: 35%; margin-left: 35%; border-color: red;">
		<br><br><br>
		<div id = "container" class="container">
		  <div class="row">
		    <div class="col-lg">
		    	<img src="{% static '/images/foodPillars.png' %}" alt="AboutUs" style="width: 50%;">
		    	<br><br>
		      <h4>Easy Food</h4>
		      <hr style="margin-right: 35%; margin-left: 35%; border-color: red; margin-top: 5px;">
		      <p>Kalian Bakal sangatlah puas dengan aplikasi kami. Milih makanan dijamin gampang banget. Restorannya pun sangatlah terpercaya</p>
		    </div>
		    <div class="col-lg">
		    	<img src="{% static '/images/transactionPillars.png' %}" alt="AboutUs" style="width: 50%;">
		    	<br><br>
		      <h4>Easy Transaction</h4>
		      <hr style="margin-right: 35%; margin-left: 35%; border-color: red; margin-top: 5px;">
		      <p>Kalian Bakal sangatlah puas dengan aplikasi kami. Cara bertransaksi mudah dan aman banget. Jangan sampai takut kalo belanja dengan aplikasi kami</p>
		    </div>
		    <div class="col-lg">
		    	<img src="{% static '/images/pickPillars.png' %}" alt="AboutUs" style="width: 50%;">
		    	<br><br>
		      <h4>Easy Pick</h4>
		      <hr style="margin-right: 35%; margin-left: 35%; border-color: red; margin-top: 5px;">
		      <p>Kalian Bakal sangatlah puas dengan aplikasi kami. Kalian bingung mau makan apa tinggal pilih. Gaperlu ribet, semua makanan ada!!</p>
		    </div>
		  </div>
		</div>
	</div>

	<div class = "lowermain_visi">
		<img src="{% static '/images/visipict.jpg' %}" alt="AboutUs" style="width: 50%; float: left; padding-right: 5%;">
		<h4>Visi</h4>
		<hr style="margin-right: 40%; margin-left: 50%; border-color: red; margin-top: 5px;">
		<p>Melayani anda dengan sepenuh hati tanpa adanya pamrih dan selalu memberikan pelayanan  yang terbaik. Selain itu, visi lainnya yaitu kami membuat hidup anda jauh lebih baik, aman, nyaman serta yang terpenting, Instant. Dengan ini, kehidupan akan menjadi lebih baik dan tentram</p>
	</div>

	<div class = "lowermain_misi">
		<img src="{% static '/images/misipict.jpg' %}" alt="AboutUs" style="width: 50%; float: right; padding-left: 5%;">
		<h4 style="text-align: right;">Misi</h4>
		<hr style="margin-right: 50%; margin-left: 40%; border-color: red; margin-top: 5px;">
		<p style="text-align: right;">Memberikan Pelayanan yang baik serta interaktif kepada para pelanggannya serta memberikan kemudahan dalam pengaksesan website agar pelanggan tidak kebingungan. Selain itu, Memberikan pelanggan kepuasan untuk bisa memilih dan melakukan sampai tahap pengiriman yang aman dan nyaman </p>
	</div>


	<!-- Extra Javascript Darkmode  -->
	<div class="container-xl restoran">
		<div class="row text-right">
			<div class="col-sm-12">
				<button id="button" class="button" onclick="myFunction()">Dark mode</button>
			</div>
		</div>
	</div>

	<br>
	<br>

	<script>
		function myFunction() {
			var body = document.getElementById('body').style.backgroundColor;
			if (body == 'rgb(19, 41, 61)') {
				document.getElementById('body').style.backgroundColor = '#F3F3F3';
				document.getElementById('body').style.color = 'black';
				document.getElementById('upper').style.backgroundColor = 'lightgrey';
				document.getElementById('middlemain').style.backgroundColor = 'lightgrey';
				document.getElementById('container').style.backgroundColor = 'lightgrey';
				document.getElementById('button').innerHTML = "Dark Mode";
			} else {
				document.getElementById('body').style.backgroundColor = '#13293D';
				document.getElementById('body').style.color = '#F3F3F3';
				document.getElementById('upper').style.backgroundColor = '#18435A';
				document.getElementById('middlemain').style.backgroundColor = '#18435A';
				document.getElementById('container').style.backgroundColor = '#18435A';
				document.getElementById('button').innerHTML = "Light Mode";
			}
		}
	</script>

	<hr>
</body>

{% include "base.html" %}

extra/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <link rel="stylesheet" href="{% static '/css/styles.css' %}">
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous"/>

    <!-- Make it Responsive -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

  </head>
  <body>
    <div class="containerFooter">
      <div class="row">
          <div class="col-sm">
            <h3>OrderIn</h3>
            <br>
            <p style="text-align: left;">
              Pandemi membuat banyak bisnis kuliner gulung tikar, para konsumen juga kesulitan untuk mencari makanan di luar. Kami membuat web yang dapat menghubungkan antara pembeli dan penjual, seorang pembeli tidak perlu keluar rumah untuk mendapatkan makanan, cukup mengakses web kami di laptop atau smartphone masing-masing. Terima Kasih
            </p>
          </div>
          <div class="col-sm">
            <h3>Features</h3>
            <br>
            <a href="{% url 'ppw:index' %}" style="color: white; font-size: large;">Home </a> <br><br>
            <a href="{% url 'keranjang:keranjang' %}" style="color: white; font-size: large;">Keranjang</a> <br><br>
            <a href="{% url 'loginApp:login'%}" style="color: white; font-size: large;">Log In</a> <br><br>
            <a href="{% url 'loginApp:register'%}" style="color: white; font-size: large;">Sign Up</a> <br><br>
            <a href="{% url 'extra:aboutus'%}" style="color: white; font-size: large;">About Us</a> <br><br>
            <a href="{% url 'extra:helpcenter'%}" style="color: white; font-size: large;">Help Center</a> <br><br>
          </div>
          <div class="col-sm" >
            <h3>Contact Us</h3>
            <br> 
            <div>
            <a href="https://line.me/id/" style="color: white">
              <img src="{% static '/images/line.png' %}" style="width: 35px;" > LINE APPS
            </a>
            <br><br>
            <a href="https://web.whatsapp.com/" style="color: white">
              <img src="{% static '/images/whatsapp.png' %}" style="width: 35px; text-align: left;" > WHATSAPP
            </a>
            <br><br>
            <a href="https://www.instagram.com/kesegaran.fasilkom/?hl=id" style="color: white">
              <img src="{% static '/images/instagram.png' %}" style="width: 35px;" > INSTAGRAM 
            </a>
            </div>
          </div>
      </div>
    </div>
    <div class="FooterCopyRight">
      <hr style="background-color: white;  margin-top: 0px;">
      <p>© 2020 Copyright: bangdjango.herokuapp.com/</p>
    </div>
  </body>
</html>

extra/templates/collections.html
{% include "navbar.html" %}
{% load static %}
 
<head>
	<link rel="stylesheet" href="{% static '/css/styles.css' %}">
</head>
<hr>
<div class = "middlemain2">

	<form action = '' method="POST">


	<div class="coloumn" style="background-color: lightgrey; padding-bottom: 25px;">

	  		<h3 align="center" style="background-color: #BD5555; color: white; padding-top: 20px; padding-bottom: 20px;">QnA Forms</h3>

			{% csrf_token %}

			<div class="QnA">
				<br>
			<p>Question :</p>
			{{form.Question}}

			<br>
			<br>

			<p>Answer : </p>
			{{form.Answer}}
			<br>
			<br>
			<button class="btn btn-info">
				<a href="{% url 'extra:helpcenter'%}"style="color: white; ">Back</a>
			</button>
			<input type = "submit" class="btn btn-primary" >
			</div>
			

		</div>

	</form>
	<hr>

	<div class="questColl">
		<h3>Question Collection</h3>
		<br>

		{% for item in result %}
		<div class="itemColl">
			<p style="color: white;">Question :</p>
			<h4>{{item.Question}}</h4>
			<br>
			<div style="background-color: white;">
				<button class="btn btn-warning">
					<a href="{% url 'extra:delete' item.id %}" style="color: black;">Delete</a>
				</button>
			</div>
			<br>

		</div>
		<br>
			{% endfor %}
	</div>

</div>

<hr>

{% include "base.html" %}

extra/templates/deleting.html
{% include "navbar.html" %}
{% load static %}

<head>
	<link rel="stylesheet" href="{% static '/css/styles.css' %}">
</head>
<br>
<h4 style="width: 50%; background-color: #BD5555; color : white; margin-left: auto; margin-right: auto; text-align: center; margin-bottom: 0px;" >DELETE QUESTION</h4>

<form action = '' method="POST">


  <div class="coloumn" style="background-color: lightgrey; width: 50%; margin-left: auto; margin-right: auto; text-align: center; padding-bottom: 20px;">

		{% csrf_token %}

		<h4 style="color: red; padding-top: 20px;" >WARNING!!!!!</h4>
		<strong>ARE YOU SURE WANTS TO DELETE</strong>
		<br>
		<br>

		<div align="center">
			<button class="btn btn-primary">
				<a href='{% url "extra:collections" %}' style="color:white">Cancel</a>
			</button>

			<input type = "submit" class="btn btn-primary" name = "Confirm">
		</div>
	</div>

</form>
<br>

extra/templates/helpcenter.html
{% load static %}
{% include "navbar.html" %}

<head>
	<link rel="stylesheet" href="{% static '/css/styles.css' %}">
</head>
<img src="{% static '/images/uppercover2.png' %}" alt="HelpCenter" style="padding: 0px 15% 0px 15%; width: 100%;" >

<body id="body">
	
	<div class = "middlemain2">
		<hr>
		<form action = '' method="POST">

		  <div id = "coloumn" class="coloumn" style="background-color: lightgrey; padding-bottom: 20px;">
		  		<h4 align="center" style="background-color: #BD5555; color : white;">Feel Free to Give us a Question</h4>
				{% csrf_token %}
				<br>
				{{form.Question}}
				<br>
				<br>
				<input type = "submit" class="btn btn-primary" >
				<button class="btn btn-info">
					<a href="{% url 'extra:collections'%}" style="color: white; ">QnA</a>
				</button>
			</div>
		</form>

		<hr>

		<div class="container">
		  <div class="row">
		    <div class="col-sm">
		      <h4 style="color: black">Frequently Ask</h4>
		    </div>
		  </div>
		  <br>


	{% for item in result %}

		<div class="container1" style="margin-bottom: 10px;">
		  <div class="row">
		    <div class="col-sm">
				<button class="accordion">{{item.Question}}</button>
				<div class="panel">
				  <p>{{item.Answer}}</p>
				</div>
		    </div>
		  </div>
		</div>


	{% endfor %}

	</div>

	<!-- Extra Javascript Accordian -->
	<script>
	var acc = document.getElementsByClassName("accordion");
	var i;

	for (i = 0; i < acc.length; i++) {
	    acc[i].onclick = function(){
	        this.classList.toggle("active");
	        this.nextElementSibling.classList.toggle("show");
	  }
	}
	</script>

	</div>
	<br>

	<!-- Extra Javascript Darkmode  -->
	<div class="container-xl restoran">
		<div class="row text-right">
			<div class="col-sm-12">
				<button id="button" class="button" onclick="myFunction()">Dark mode</button>
			</div>
		</div>
	</div>

	<br>
	<br>

	<script>
		function myFunction() {
			var body = document.getElementById('body').style.backgroundColor;
			if (body == 'rgb(19, 41, 61)') {
				document.getElementById('body').style.backgroundColor = '#F3F3F3';
				document.getElementById('button').innerHTML = "Dark Mode";
			} else {
				document.getElementById('body').style.backgroundColor = '#13293D';
				document.getElementById('button').innerHTML = "Light Mode";
			}
		}
	</script>

	<hr>


</body>

{% include "base.html" %}